Fix getting PID from empty PID file (#22)
* Check $pid variable in case PID file is empty
* Fix issue with keeping PID file with empty PID inside

diff --git a/SOURCES/anicorn b/SOURCES/anicorn
--- a/SOURCES/anicorn
+++ b/SOURCES/anicorn
@@ -180,15 +180,13 @@ checkPIDFile() {
 
   pid=$(getPID)
 
-  if [[ "$pid" == "" && -e "$pid_file" ]] ; then
+  if [[ -n "$pid" ]] ; then
+      if ! isUnicornProcess "$pid" ; then
+          log "[ERROR] Running process with PID ${pid} is not a Unicorn"
+          exit 1
+      fi
+  else
       rm -f "$pid_file"
-  fi
-
-  if [[ "$pid" != "" ]] ; then
-    if ! isUnicornProcess "$pid" ; then
-      log "[ERROR] Running process with PID ${pid} is not a Unicorn"
-      exit 1
-    fi
   fi
 }
 
@@ -410,7 +408,7 @@ getPID() {
 
   pid=$(tr -d '\n\r' < "$pid_file")
 
-  if [[ ! -e "/proc/$pid" ]] ; then
+  if [[ ! -e "/proc/$pid" || ! -n "$pid" ]] ; then
     echo ""
     return
   fi
