Improvements

diff --git a/SOURCES/anicorn b/SOURCES/anicorn
--- a/SOURCES/anicorn
+++ b/SOURCES/anicorn
@@ -3,7 +3,7 @@
 ########################################################################################
 
 APP="Anicorn"
-VER="1.1.0"
+VER="2.0.0"
 DESC="Simple utility for starting/restarting Unicorn"
 
 ########################################################################################
@@ -45,8 +45,13 @@ DELAY_START=60
 DELAY_STOP=30
 DELAY_SIGNAL=5
 DELAY_MONITOR=5
+DELAY_PID_MONITOR=15
 
+# Path to temporary file for output
 TMP_OUTPUT="/tmp/anicorn.output"
+
+# Path to anicorn binary
+BIN="$0"
 
 ########################################################################################
 
@@ -62,19 +67,29 @@ disable_monitoring=""
 
 ########################################################################################
 
+SUPPORTED_ARGS="config watchdog !version !help"
+SHORT_ARGS="c:config w:watchdog h:!help v:!version"
+
+########################################################################################
+
 main() {
-  if [[ "$1" == "-v" || "$1" == "--version" ]] ; then
+  if [[ -n "$version" ]] ; then
     about
     exit 0
   fi
 
-  if [[ "$1" == "-h" || "$1" == "--help" || $# -eq 0 ]] ; then
+  if [[ -n "$help" || $# -eq 0 ]] ; then
     usage
     exit 0
   fi
 
-  if [[ "$1" == "-c" ]] ; then
-    unicorn_config="$2"
+  if [[ -n "$watchdog" ]] ; then
+    monitorStoppedUnicorn "$watchdog"
+    exit 0
+  fi
+
+  if [[ -n "$config" ]] ; then
+    unicorn_config="$config"
   else
     unicorn_config="$1"
   fi
@@ -145,7 +160,8 @@ checkPIDFile() {
 # Echo: No
 startUnincorn() {
   if [[ -e "$pid_file" ]] ; then
-    log "Unicorn already works, waiting for TERM signal..."
+    log "Unicorn already works, restarting..."
+    restartUnicron
     return
   fi
 
@@ -186,7 +202,7 @@ restartUnicron() {
   pid=$(getPID)
 
   if [[ -z "$pid" ]] ; then
-    log "[ERROR] Looks like Unicorn is already down."
+    log "[ERROR] Looks like Unicorn is already down"
     return 1
   fi
 
@@ -203,6 +219,7 @@ restartUnicron() {
   fi
 
   log "[ERROR] Can't restart Unicorn"
+  
   return 1
 }
 
@@ -235,20 +252,16 @@ monitorUnicorn() {
 # Code: No
 # Echo: No
 sigHandler() {
-  local ec
-
   log "Got TERM signal"
 
   # Temporary disable monitoring
   disable_monitoring=true
 
-  restartUnicron
-
-  ec=$?
+  log "Running watchdog process"
 
   log "$APP is now getting shutdown"
 
-  exit $ec
+  exit 0
 }
 
 # Check if Unicorn is works
@@ -317,6 +330,47 @@ isUnicornRestarted() {
   return 1
 }
 
+# Run anicorn as process monitor current Unicorn process
+#
+# 1: PID (Number)
+#
+# Code: No
+# Echo: No
+runWatchdog() {
+  local pid
+
+  pid=$(getPID)
+
+  if [[ -z "$pid" ]] ; then
+    log "[ERROR] Can't start watchdog: can't find Unicorn PID"
+    return
+  fi
+
+  $BIN --watchdog "$pid" &>/dev/null &
+
+  disown
+}
+
+# Terminate Unicorn if it isn't restarted
+#
+# 1: PID (Number)
+#
+# Code: No
+# Echo: No
+monitorStoppedUnicorn() {
+  local pid="$1"
+
+  for i in $(seq 0 $DELAY_PID_MONITOR) ; do
+    if [[ ! -e "/proc/$pid" ]] ; then
+      exit 0
+    fi
+
+    sleep 1
+  done
+
+  kill -TERM "$pid"
+}
+
 # Read PID from PID file
 #
 # Code: No
@@ -377,9 +431,9 @@ show() {
 # Echo: No
 usage() {
   show ""
-  show "${CL_BOLD}Usage:${CL_NORM} anicorn unicorn-conf"
+  show "${CL_BOLD}Usage:${CL_NORM} anicorn ${CL_CYAN}unicorn-conf${CL_NORM}"
   show ""
-  show "Params" $BOLD
+  show "Arguments" $BOLD
   show ""
   show "  ${CL_CYAN}unicorn-conf${CL_NORM}  Path to Unicorn configuration file"
   show ""
@@ -387,6 +441,9 @@ usage() {
   show ""
   show "  anicorn /srv/projects/example/current/config/unicorn.rb"
   show "  Run Unicorn with Anicorn" $DARK
+  show ""
+  show "  anicorn -c /srv/projects/example/current/config/unicorn.rb"
+  show "  Run Unicorn with Anicorn using Unicorn compatible syntax" $DARK
   show ""
 }
 
@@ -399,10 +456,118 @@ about() {
   show "${CL_BL_CYAN}$APP${CL_NORM} ${CL_CYAN}$VER${CL_NORM} - $DESC"
   show ""
   show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
-  show "Essential Kaos Open Source License <http://essentialkaos.com/ekol>" $DARK
+  show "Essential Kaos Open Source License <https://essentialkaos.com/ekol>" $DARK
   show ""
 }
 
-########################################################################################
+# Show warning message about unsupported argument
+#
+# 1: Argument name (String)
+#
+# Code: No
+# Echo: No
+showArgWarn() {
+  error "Unknown argument $1" $RED
+  exit 1
+}
 
-main "$@"
+## ARGUMENTS PARSING 3 #################################################################
+
+[[ $# -eq 0 ]] && main && exit $?
+
+unset arg argn argm argv argt argk
+
+argv="$*" ; argt=""
+
+while [[ -n "$1" ]] ; do
+  if [[ "$1" =~ \  && -n "$argn" ]] ; then
+    declare "$argn=$1"
+
+    unset argn && shift && continue
+  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
+    argm=${1:1}
+
+    if [[ \ $SHORT_ARGS\  =~ \ $argm:!?([a-zA-Z0-9_]*) ]] ; then
+      arg="${BASH_REMATCH[1]}"
+    else
+      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
+      shift && continue
+    fi
+
+    if [[ -z "$argn" ]] ; then
+      argn=$arg
+    else
+      [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
+      argn=$arg
+    fi
+
+    if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
+      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
+      shift && continue
+    fi
+
+    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
+      declare "$argn=true" ; unset argn ; argk=true
+    else
+      unset argk
+    fi
+
+    shift && continue
+  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
+    arg=${1:2}
+
+    if [[ $arg == *=* ]] ; then
+      IFS="=" read -ra arg <<< "$arg"
+
+      argm="${arg[0]}" ; argm=${argm//-/_}
+
+      if [[ ! $SUPPORTED_ARGS\  =~ $argm\  ]] ; then
+        declare -F showArgWarn &>/dev/null && showArgWarn "--${arg[0]//_/-}"
+        shift && continue
+      fi
+
+      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[*]:1:99}" || declare "$argm=${arg[*]:1:99}"
+
+      unset argm && shift && continue
+    else
+      arg=${arg//-/_}
+
+      if [[ -z "$argn" ]] ; then
+        argn=$arg
+      else
+        [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
+        argn=$arg
+      fi
+
+      if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
+        declare -F showArgWarn &>/dev/null && showArgWarn "--${argn//_/-}"
+        shift && continue
+      fi
+
+      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
+        declare "$argn=true" ; unset argn ; argk=true
+      else
+        unset argk
+      fi
+
+      shift && continue
+    fi
+  else
+    if [[ -n "$argn" ]] ; then
+      [[ -n "${!argn}" && $MERGEABLE_ARGS\  =~ $argn\  ]] && declare "$argn=${!argn} $1" || declare "$argn=$1"
+
+      unset argn && shift && continue
+    fi
+  fi
+
+  argt="$argt $1" ; shift
+
+done
+
+[[ -n "$argn" ]] && declare "$argn=true"
+
+unset arg argn argm argk
+
+[[ -n "$KEEP_ARGS" ]] && main "$argv" || main "${argt:1:9999}"
+
+########################################################################################
